### ISSUE TITLE
Latest LTS misreported as JDK 11

### ISSUE THREAD

**Issue by d3vel0per** [adoptium/api.adoptium.net#172]
**Describe the bug**
API's are still reporting the latest LTS as JDK 11

**To Reproduce**
```shell
❯ curl -X 'GET' \
>   'https://api.adoptium.net/v3/info/available_releases' \
>   -H 'accept: application/json'

{
    "available_lts_releases": [
        8,
        11
    ],
    "available_releases": [
        8,
        11,
        16,
        17
    ],
    "most_recent_feature_release": 17,
    "most_recent_feature_version": 17,
    "most_recent_lts": 11,
    "tip_version": 18
}
```

**Expected behavior**
This is what I think it should look like:
```json
{
    "available_lts_releases": [
        8,
        11,
        17
    ],
    "available_releases": [
        8,
        11,
        16,
        17
    ],
    "most_recent_feature_release": 17,
    "most_recent_feature_version": 17+35,
    "most_recent_lts": 17,
    "tip_version": 18
}
```

**Comment by tushev** [comment]
@johnoliver it seems that https://api.adoptopenjdk.net/v3/info/available_releases still has
```
"available_lts_releases": [
    8,
    11
  ],
```

There are still tools that use old API (for instance, my updater still uses it because it's the only API at the moment that provides IBM Semeru runtimes), so maybe it's better to fix it there as well if possible.

**Comment by tellison** [comment]
@tushev please open an issue at [the AdoptOpenJDK repo](https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/new/choose)
