### ISSUE TITLE
Version filter no longer supports `semver` version string

### ISSUE THREAD

**Issue by viceice** [adoptium/api.adoptium.net#492]
**Describe the bug**
The api recently changed to no longer accept the semver string from `v3/info/release_versions` as filter parameter for other apis like
`v3/assets/version/18.0.2+101`.  Those now return a 404 instead.

We use those api to suggest java updates, but they started failing recently

**To Reproduce**
1. Go to '[...](https://api.adoptium.net/q/swagger-ui/#/Assets/searchReleasesByVersion)'
2. Click on 'Try it out'
3. Scroll down to 'version'
4. Add `18.0.2+101`
5. Scroll down to `Execute`
6. See 404

**Expected behavior**
Allow using `semver` string instead of `openjdk_version`, which now seems to differ

**Screenshots**
![image](https://user-images.githubusercontent.com/1798109/187373955-3f24d455-3de7-495f-88fb-4d70dd25d056.png)
![image](https://user-images.githubusercontent.com/1798109/187374024-231d99bf-ed9d-4eef-a161-3b741123be05.png)

**Device (please complete the following information):**
 - OS: Linux, Windows
 - Browser Chrome, curl
 - Version latest available, doesn't matter

**Additional context**

**Comment by viceice** [comment]
It works for java 8 semver like `8.0.342+7`

https://api.adoptium.net/v3/assets/version/8.0.342%2B7?architecture=x64&heap_size=normal&image_type=jre&os=linux&page=0&page_size=10&project=jdk
![image](https://user-images.githubusercontent.com/1798109/187376687-be71c714-145f-4ffa-a881-f569925841a7.png)

**Comment by viceice** [comment]
OK, it seems only `18.0.2+101` is having the issue

**Comment by viceice** [comment]
no, `17.0.4+101` too. So it seems it's happening for all versions where the semver build metadata is greater than 100, so it's different to the `openjdk_version` field

**Comment by johnoliver** [comment]
This is a bit of an issue. So far, we have actually taken the openjdk version as an argument there. The documentation wording is a bit ambiguous as it says:

```
Java version range (maven style)
```

Here "maven style" actually refers to the method of defining the filter and not the version style. 

Due to Adoptium using semver and making the openjdk version fit within semver, this could get complex. I think the best solution here may be to add a query parameter such as

```
semver=true
```

that a user can provide in their query to indicate to the query that the user is providing a semver rather than openjdk version. However leave the default functionality unchanged for backwards compatibility.

@viceice would that work for you?

**Comment by viceice** [comment]
sounds good to me

**Comment by mkjor** [comment]
Unfortunately, I encountered the same problem in our build pipelines (managed by Renovate ;-)) . In this way the `semver` is no longer usable.

**Comment by viceice** [comment]
when this will be gone life?

**Comment by karianna** [comment]
Up to @johnoliver when he deems main to be stable enough to push, but probably in the next few weeks at the latest
